version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./config/dev.docker.env
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./config/dev.docker.env
    volumes:
      - "./db-data:/data/db"
